// <auto-generated />
namespace Wirly.web.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.2-31219")]
    public sealed partial class AddProjectstoFiles : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(AddProjectstoFiles));
        
        string IMigrationMetadata.Id
        {
            get { return "201502270055162_Add Projects to Files"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
